### ISSUE TITLE
Can't make it

### ISSUE THREAD

**Issue by Kilkenni** [mmpx12/twitter-media-downloader#15]
![Screenshot 2023-02-04_13-01-28_8](https://user-images.githubusercontent.com/12563370/216763475-ac3d2bee-e492-47b6-83ad-7df9d521a9f6.png)

When I try to build TWMD, it throws this error:

```
>$ make
go build -ldflags="-w -s"
# twmd
./twmd.go:30:2: version redeclared in this block
	./gui.go:16:7: other declaration of version
./twmd.go:210:6: main redeclared in this block
	./gui.go:454:6: other declaration of main
make: *** [Makefile:2: build] Error 1
```

I use golang 1.20.
Prebuilt version works fine but afaik there is no GUI version, is there?

Also, is it possible to add a date interval option?

**Comment by mmpx12** [comment]
Same as  https://github.com/mmpx12/twitter-media-downloader/issues/10#issuecomment-1341563444  (i need to update the Makefile). Use:

```sh
# for the command line
$ go build -ldflags="-w -s" twmd.go

# for the gui
go build -ldflags="-w -s" -o twmd gui.go
```


There is not yet gui version in release since i didn't made a release yet. It will be in next release. 

Adding date intervale is not so easy but will try to implement it in next release.

**Comment by mmpx12** [comment]
Makefile now working. For date range I will  notimplement it soon. Feel free to open pr
