### ISSUE TITLE
Only downloaded 90 files

### ISSUE THREAD

**Issue by zal-byte** [mmpx12/twitter-media-downloader#5]
User has 1000+ image, but when i run the program, only 90 item downloaded

@melty_pot

![Screenshot from 2022-08-19 02-25-09](https://user-images.githubusercontent.com/61190912/185477888-85db326b-5f34-426b-ab08-a22566d1e4e5.png)

Does this have to be logged in twitter account to get better results?

Thanks.

**Comment by mmpx12** [comment]
Without api, user tweet are limited (was around 3000) but i think twitter "fixed" it.
Also if tweet didnt have image, they will be count in the 3000. 
Since this is based on [twitter-scrapper](https://github.com/n0madic/twitter-scraper) i think you should open this issue in twitter-scrapper repo.
I am closing this issue because i can do nothing to fixed it.

**Comment by zal-byte** [comment]
okay, thanks for the information
